#!/usr/bin/env /bin/sh
set -e
PATH="/usr/local/bin:$PATH"
dir="$(git rev-parse --git-dir)"
trap 'rm -f "${dir}/tags.$$"' EXIT INT TERM
#ctags --tag-relative -Rf.${dir}/tags.$$ --exclude=.git --languages=-javascript,sql
git ls-files | ctags --tag-relative -L - -f${dir}/tags.$$ --languages=-javascript,sql
mv ${dir}/tags.$$ ${dir}/tags
exit 0
